backend/plataforma.mentoria/pom.xml
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/User.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/UserRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/SecurityConfig.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/SecurityFilter.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/TokenService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/util/UserRole.java
backend/plataforma.mentoria/src/main/resources/application.properties

T1 - Configuração Inicial e Dependências
T2 - Modelagem de Usuário (Model)
T3 - Criação de Repositório de Usuário
T4 - Configuração Central do Spring Security
T5 - Implementação do Serviço JWT
T6 - Criação do Filtro de Autenticação JWT

Implementação de T1, T2, T3, T4, T5, T6

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/AuthController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/AuthDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/LoginResponseDTO.java
backend/plataforma.mentoria/src/main/resources/application.properties

Duas novas classes:
AuthDTO: classe responsável por receber os dados de login (e-mail e senha).
LoginResponseDTO: encapsula a resposta de autenticação, contendo o token gerado.
Funcionalidades: Foi adicionado um novo endpoint POST /login no controller
Que recebe as credenciais do usuário via AuthDTO.
Autentica o usuário utilizando o AuthenticationManager do Spring Security.
Caso a autenticação seja bem-sucedida, gera um token JWT.
Retorna o token encapsulado em um LoginResponseDTO.

Implemetação de T8 - Autenticação de Usuário

---

.github/pull_request_template.md

Este PR adiciona o template padrão para mensagens de Pull Request no repositório principal, facilitando a padronização da comunicação e garantindo que as informações essenciais sejam fornecidas em cada PR.
---
- N/A
---
- Adição de template para PRs;
- Padronização do processo de revisão e merge;
- Facilita rastreamento e documentação das mudanças.
---
---
---
N/A

[docs]: adiciona template padrão de Pull Request

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/UserDTO.java

--- O PR tem como objetivo aumentar a complexidade da senha, para trazer um nível a mais de segurança para os usuários. E também melhora a estabilidade do banco de dados, fazendo com que nomes tenham no mínimo tamanho 3
- N/A
--- 
- A validação da senha força a criação de senhas fortes e complexas, protegendo diretamente a conta do usuário contra acessos não autorizados. 
- Já a validação do nome com tamanho mínimo de 3 caracteres é importante para garantir a integridade e a qualidade dos dados, evitando o cadastro de informações inválidas ou sem sentido no sistema.
--- 
---
---
- Closes #72

fix: Validação de senha e nome T25

---

frontend/src/app/auth/auth.service.ts
frontend/src/app/auth/register/register.component.ts
frontend/src/app/auth/user.ts

Integrando a lógica do frontend para o backend da página de cadastro.
---
---
---
- Closes #47

Integração da lógica de cadastro com o Backend

---

frontend/src/app/auth/auth.service.ts
frontend/src/app/auth/login/login.component.html
frontend/src/app/auth/register/register.component.html
frontend/src/app/auth/register/register.component.ts

Corrigi o link na pagina de cadastro para poder redirecionar para login, e corrigir a pagina de login para poder entrar no home
---
Corrigi o link na pagina de cadastro para poder redirecionar para login, e corrigir a pagina de login para poder entrar no home
---
---
---
- Refers to #44 
- Refers to #52

Corrigindo bugs nas paginas de cadastro e login

---

frontend/src/app/auth/login/login.component.css
frontend/src/app/auth/login/login.component.html
frontend/src/app/auth/login/login.component.ts

Coloca novamente as validações na página de login, validações de email e tamanho da senha para evitar chamadas desnecessárias da API.
---
N/A
---
N/A
---
---
---
- Closes #50 #51

[feat][frontend]: Reaplica validação na página de login

---

frontend/src/app/auth/auth.service.ts
frontend/src/app/auth/login/login.component.html
frontend/src/app/auth/login/login.component.ts
frontend/src/app/auth/register/register.component.html

…rro do auth-service
Adicionado mensagens de erro no login, e ajustes feitos no auth-service.
---
- Corrige problema no interceptor do auth-service que não estava propagando a exception do backend, apenas retornando true/false, não dando para identificar qual era o tipo de erro.
---
Mensagem de erro explícita no login, se errou as credenciais ou o servidor está fora do ar.
---
---
---
- Closes #53

[feat][frontend]: Adicionando mensagem de erro no login e ajustando auth-service

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/UserDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/TokenService.java

O Issuer token foi de "housing" para "Mentoria"
O Validador de senhas do backend é equivalente ao do front, fix
---
- Corrige Issuer Token em TokenService
- Corrige password em UserDTO
---
N/A
---
---
---
-  N/A

fix: Melhorias referentes a nova iteração

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/UserDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentor.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentored.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Person.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/User.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/SecurityConfig.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/AuthService.java

Implementa a hierarquia de entidades Person, Mentor e Mentored conforme especificado nas issues T1 e T5. Remove o campo `name` da entidade User e UserDTO, criando uma estrutura mais organizada onde Person serve como classe base para Mentor e Mentored, que são associadas à entidade User.
---
N/A
---
- Refatora estrutura de dados removendo campo `name` de User/UserDTO
- Cria hierarquia de entidades mais organizada com Person como base
- Melhora separação de responsabilidades entre User (autenticação) e Person (dados pessoais)
- Atualiza configurações de segurança para suportar nova estrutura
---
---
---
- Closes #90
- Closes #94

[feat][backend]: implementa hierarquia de entidades Person, Mentor e Mentored

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentoredDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/exceptions/MentoredNotFoundException.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/MentoredMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentored.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentoredRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredService.java

- Foi criado o Mentored Service  e o mentored repository com as funções básica, além de outras classes auxiliares.
---
- N/A
---
- N/A
---
---
---
- Closes #96 #93

[feat][backend]: Criados o Mentored Service e o Mentored Repository

---

frontend/src/app/auth/mentor.ts
frontend/src/app/auth/register/register.component.ts
frontend/src/app/auth/user.ts

Criar uma classe mentor para receber os dados do front e passar para o backend.
---
Correção no nome da variável name na interface User no front, afim de alinhar com o nome do backend e evitar conflitos.
---
N/A
---
---
---
- Closes #104

[feat][frontend]: Criar uma Classe mentor, que herda de user, para servir de conexão com backend

---

frontend/src/app/auth/mentored.ts

Uma nova classe, mentored.ts, que irá se conectar para o backend passando as informações: cpf, data de nascimento, curso e o sumario do mentorado.
---
- N/A
---
- 
---
---
---
- Closes #52

feat: Criando a classe mentored.ts, para a conexão com o backend

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentorDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentoredDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/exceptions/AttributeAlreadyInUseException.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/exceptions/EntityNotFoundException.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/MentoredMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Person.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentoredRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredService.java

- Adicionei o campo do email que não estava presente na classe abstrada, e adicionei as validações.
---
- N/A
---
- Além de adicionar o email, criei 2 classes gerais de exception para manter o padrão DRY.
---
---
---

[fix][backend]: Adicionado campo do email que estava faltando e validações no mentored service.

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentorRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredService.java
frontend/src/app/auth/edit-mentored-profile-modal/edit-mentored-modal.component.css
frontend/src/app/auth/edit-mentored-profile-modal/edit-mentored-modal.component.html
frontend/src/app/auth/edit-mentored-profile-modal/edit-mentored-modal.component.ts

Criação de modal mentorado para edição de informações de mentorado
Resolução de bugs de mentorado
---
- Corrige o MentoradoService 
---
N/A
---
---
---
- Closes #109

feat and fix: modal mentorado e correção em serviceMentored

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentorRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentorService.java

Adiciona a pesquisa por filtros de mentores para mentorados
---
N/A
---
N/A
---
---
---
- Refers to #128

[feat][backend] Adicionando a pesquisa por filtro de mentores para os mentorados

---

frontend/src/app/auth/auth.service.ts
frontend/src/app/auth/register/mentor-register/mentor-register/mentor-register.component.html
frontend/src/app/auth/register/mentor-register/mentor-register/mentor-register.component.ts
frontend/src/app/auth/register/mentored-register/mentored-register/mentored-register.component.html
frontend/src/app/auth/register/register.component.ts
frontend/src/app/entity/mentor.ts
frontend/src/app/entity/mentored.ts
frontend/src/app/entity/user.ts

Pequenas alterações de conformidade do front com o back e integração da criação do mentor com o back
---
---
- Closes #138

Integração do cadastro do mentor com o backend

---

frontend/src/app/auth/auth.service.ts

Este PR ajusta o `AuthService` para corretamente processar e expor a `role` de usuário (`MENTOR`/`MENTORED`) recebida através do token JWT. A aplicação não conseguia diferenciar os perfis de usuário, o que impedia a implementação de lógicas de acesso distintas.
Agora, o serviço decodifica o token no momento do login, armazena a `role` e a disponibiliza para o restante da aplicação através de métodos auxiliares. Isso possibilita a implementação de controle de acesso baseado em perfil (RBAC) em rotas e componentes.
---
- O `AuthService` agora decodifica o token JWT para extrair e armazenar a `claim` de `role`.
- Os "Route Guards" (guardas de rota) foram atualizados para verificar a `role` do usuário, permitindo o acesso apenas a perfis autorizados.
---
- Criação de métodos auxiliares no …

[fix][frontend]: auth.service

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentoredRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredService.java

fix: MentoredService e MentoryRepository
---
- Corrige um erro no service
---
- [...]
---
---
---
- Closes #XX  

fix: MentoredService e MentoryRepository

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentorDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentoredDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/MentorMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/MentoredMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/UserRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/SecurityFilter.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/TokenService.java
frontend/src/app/auth/auth.service.ts
frontend/src/app/auth/delete-mentor-modal/delete-mentor-modal.component.css
frontend/src/app/auth/delete-mentor-modal/delete-mentor-modal.component.html
frontend/src/app/auth/delete-mentor-modal/delete-mentor-modal.component.ts
frontend/src/app/auth/delete-mentored-modal/delete-mentored-modal.component.css
frontend/src/app/auth/delete-mentored-modal/delete-mentored-modal.component.html
frontend/src/app/auth/delete-mentored-modal/delete-mentored-modal.component.ts
frontend/src/app/auth/register/mentored-register/mentored-register/mentored-register.component.ts
frontend/src/app/profile/profile.component.css
frontend/src/app/profile/profile.component.html
frontend/src/app/profile/profile.component.ts
frontend/src/app/profile/profile.service.ts

Integra a lógica de exclusão de mentores e mentorados, conectando o backend ao frontend para permitir que usuários excluam suas contas diretamente pela interface. Essa implementação adiciona os componentes modais necessários para confirmação da exclusão e realiza a comunicação com a API para executar a remoção dos dados.
---
- Corrige a ausência da funcionalidade de exclusão no frontend, que impedia os usuários de remover suas contas.
- Corrige erros de comunicação entre frontend e backend na exclusão de mentores e mentorados.
---
- Adiciona componentes modais de confirmação para exclusão de mentor e mentorado.
- Refatora a estrutura dos componentes relacionados para melhor organização e reutilização.
- Melhora a experiência do usuário ao confirmar a exclusão com modais claros e mensagens …

[feat]: Integra a lógica de excluir (backend to frontend)

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/enums/InterestAreas.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentor.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentored.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Person.java

Corrigindo InterestAreas no back
---
- Corrige o bug onde não estava sendo salvo interestAreas no backend
---
- [...]
---
---
- [ x] Alta: bloqueia deploys, corrige falhas graves ou impede o uso da aplicação
---
- Closes #XX  

Corrigindo parcialmente InterestAreas

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentorController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentorDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentoredDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/enums/InterestArea.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/MentorMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/MentoredMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentor.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentored.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Person.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentorRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentoredRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentorService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredService.java
frontend/src/app/auth/register/mentored-register/mentored-register/mentored-register.component.html
frontend/src/app/auth/register/mentored-register/mentored-register/mentored-register.component.ts
frontend/src/app/entity/mentor.ts
frontend/src/app/entity/mentored.ts

Area Interest foi refatorado
---
- Corrige o problema de interestArea não aparecer no perfil de mentor
---
- [...]
---
---
---

fix:  interestArea resolvido em Mentor

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentorController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/enums/InterestArea.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentor.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentored.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentorRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/MentoredRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentorService.java

Ajuste na exclusão em cascata de Mentor e User
---
- Corrige a exclusão em cascata de Mentor e User
---
- Remove imports não utilizados
- Adiciona enums de IntrestAreas
---
---
---
- Closes #180 
- Refers to #180

Ajuste na exclusão em cascata de Mentor e User

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentored.java
frontend/src/app/auth/register/mentor-register/mentor-register/mentor-register.component.html
frontend/src/app/auth/register/mentored-register/mentored-register/mentored-register.component.html

Ele aplica as alterações do backend no front
e corrigi pequenos bugs na hora de rodar o projeto
---
- Corrige mentored importando a biblioteca necessária para ele rodar
---
- N/A
---
---
---
- Closes #XX  

[refactor] Adiciona mais áreas de interesse no frontend

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/SessionDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/enums/Status.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/SessionMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Session.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/SessionRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/SessionService.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/repository/SessionRepositoryTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/service/SessionServiceTest.java

Nesse PR é implementado a Classe Session, seu services, seu repositório e seus testes
A classe session tem o objetivo de marcar uma sessão entre dois usuários, podem ser tanto mentorados quanto mentores
---
---
- [...]
---
---
---
- Closes #163 
- Refers to #164

Implementando a classe Sessão

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentorController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/UpdateMentorDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/UpdateMentoredDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentorService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredService.java

implementa updateMentor e updateMentored com patch . Atualiza apenas um campo, sem necessidade de sobreescrita.
---
---
implementa updateMentor e updateMentored com patch . Atualiza apenas um campo, sem necessidade de sobreescrita.
---
---
---
- Closes #XY

Implementa updateMentor e updateMentored com PATCH

---

frontend/src/app/home/home.component.css
frontend/src/app/home/home.component.html
frontend/src/app/home/home.component.ts
frontend/src/app/profile/profile.service.ts
frontend/src/styles.css

Integração da parte de busca de mentores com o backend. O mentorado seleciona a área de interesse do mentor desejado e, logo em seguida, coloca as especializações desejadas
---
Correção do UI/UX da tela, afim de deixar mais intuitiva
---
N/A
---
---
---
- Closes #XX  

[feat][frontend]: Integração do campo de busca de mentor por Área de interesse e especialização

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/SessionController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/SessionMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/SessionService.java

Este PR introduz o SessionController, um endpoint RESTful completo para o gerenciamento de sessões de mentoria. Além disso, implementa no SessionService uma lógica robusta para o ciclo de vida das sessões, garantindo que as transições de status (Pendente, Aceito, Concluído, etc.) sigam as regras de negócio definidas.
---
N/A
---
- Criação de endpoints para todas as operações CRUD (Criar, Ler, Atualizar, Deletar) para as sessões.
- Adição de endpoints específicos para consultar o histórico de sessões por mentor, mentorado ou entre ambos.
- Implementação de um endpoint PATCH para atualizar apenas o status da sessão, validando o fluxo de transição (ex: uma sessão PENDENTE só pode ser ACEITA ou REJEITADA).
- A lógica de atualização de status também foi integrada ao endpoint …

[feat][backend] T2 - Criar os componentes de Session, implementação do controller e ajustes

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/AuthController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentorController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/AuthService.java
frontend/src/app/app.routes.ts
frontend/src/app/auth/auth.service.ts
frontend/src/app/entity/responses/response-mentor.ts
frontend/src/app/entity/responses/response-mentored.ts
frontend/src/app/entity/session.ts
frontend/src/app/home/home.component.html
frontend/src/app/home/home.component.ts
frontend/src/app/sessions/session.component.css
frontend/src/app/sessions/session.component.html
frontend/src/app/sessions/session.component.ts
frontend/src/app/sessions/session.service.ts

Criação da página de criar sessão da plataforma.
---
---
- Closes #189 
- Closes #187

Criação da página de criar sessão da plataforma.

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentorController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MentoredController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/SessionController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentorSearchService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentorService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredSearchService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MentoredService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/SessionService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/contract/AuthServiceInterface.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/contract/MentorSearchServiceInterface.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/contract/MentorServiceInterface.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/contract/MentoredSearchServiceInterface.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/contract/MentoredServiceInterface.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/contract/SessionServiceInterface.java

Essa refatoração tem como objetivo separar algumas classes de services, afim de deixar o código mais modular.
---
Correção de SRP.
---
Foram criadas classes dedicas a funções de busca de mentores e mentorados, desacoplando do service do CRUD de mentor e mentorado
---
---
---
- Closes #XX  

[refactor][backend]: Criação de classes de busca para mentor e mentorado, afim de deixar o código mais modular.

---

frontend/Dockerfile

Adiciona Dockerfile para o frontend utilizando multi-stage build, otimizando a imagem gerada.
---
- N/A
---
- N/A
---
---
---

[feat][frontend]: Adiciona Dockerfile do frontend

---

backend/plataforma.mentoria/src/main/resources/application-prod.properties

Adiciona application-prod.properties
---
- N/A
---
- N/A
---
---
---
-  N/A

[feat][backend]: Adiciona application-prod.properties

---

backend/plataforma.mentoria/pom.xml

- Adiciona postgresql no pom.xml
---
- N/A
---
- N/A
---
---
---
- N/A

[feat][backend]: Adiciona postgresql no pom.xml

---

frontend/src/app/profile/profile.component.css
frontend/src/app/profile/profile.component.html
frontend/src/app/profile/profile.component.ts
frontend/src/app/session-history/session-history.component.css
frontend/src/app/session-history/session-history.component.html
frontend/src/app/sessions/session.component.css
frontend/src/app/sessions/session.component.html
frontend/src/app/sessions/session.component.ts

Este PR unifica a lógica e o estilo dos botões de **voltar**, **editar** e **excluir** na página **Profile**, além de padronizar o botão de **voltar** nas páginas **Session** e **Session History**.  
O objetivo é garantir consistência visual e de comportamento entre as diferentes telas.
---
N/A
---
- Unifica estilo e comportamento dos botões de voltar em todas as páginas.
- Padroniza botões de editar e excluir na página **Profile**.
- Padroniza botão de **voltar** nas páginas **Session** e **Session History**.
- Melhora a consistência visual da aplicação.
---
---
---

[refactor][frontend]: unifica lógica e estilo dos botões

---

backend/plataforma.mentoria/src/main/resources/application-prod.properties

- Adiciona a url do postgresql
---
- N/A
---
- N/A
---
---
---
-  N/A

[feat][backend]: Adiciona a url do postgresql

---

backend/plataforma.mentoria/src/main/resources/application-prod.properties

- Mudança da URL do banco
---
- N/A
---
- N/A
---
---
---
- N/A

[feat][backend]: Adiciona a URL Externa do banco postgresql

---

frontend/environments/environment.prod.ts

- Foi feito a conexão entre o frontend e backend
---
---
- [...]
---
---
---

fix: add o link do backend no front

---

README.md

Foi adicionado o link do site hosteado no render no readme.
---
- N/A
---
- Melhoria na documentação.
---
---
---
- Closes #208

[feat][docs]: Atualizando README.md com site

---

README.md

Foi adicionado o link do backend na documentação.
---
- N/A
---
- [...]
---
---
---

[docs]: Adicionado link do backend no README

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/exceptions/EntityNotFoundException.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/SessionService.java

O tratamento de instruções no SessionService estava usando texto duplicado, então foi utilizado o construtor padrão para evitar duplicação de código. 
---
- Corrige duplicação de código, que pode causar inconsistência futura.
---
- Refatora a exception para português, e o session Service para utilizar o construtor padrão.
---
---
---
- Closes #249

♻️ refactor(session): melhorar tratamento de exceções e formatação

---

backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/service/SessionServiceTest.java

Foram implementados os testes referentes a Session
---
-  N/A
---
-  N/A
---
---
---
- Closes to #272 

Testes para Session

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Person.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/SessionService.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/service/MentorServiceTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/service/MentoredServiceTest.java

Este PR adiciona testes unitários para os serviços principais da aplicação e aplica melhorias internas de código, visando aumentar a cobertura de testes, melhorar o encapsulamento e manter a base mais limpa.
---
- N/A
---
- Implementados testes unitários para MentorService
- Implementados testes unitários para MentoredService
- Removidas variáveis locais não utilizadas (SessionService)
- Ajustada a visibilidade de construtores para protected (Person.java)
---
---
---
- Closes #230 
- Closes #231  
- Closes #256   
- Closes #254

Implementando testes unitários em MentorService e MentoredService, removendo variáveis locais não utilizadas e ajustando visibilidade de construtores.

---

backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/exception/AttributeAlreadyInUseExceptionTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/exception/EntityNotFoundExceptionTest.java

Feito os testes para as exceptions.
---
- N/A
---
- N/A
---
---
---
- Closes #273

Implementando teste das exceptions no backend.

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/exceptions/TokenCreationException.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/TokenService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/AuthService.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/controller/SessionControllerIntegrationTest.java

- Define excessão personalizada em TokenService
- Ajusta cláusula if não utlizada em Tojen Service
- Remove imports não utlizados
---
---
---
- Closes #XX  

Define excessão personalizada em TokenService

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/MentorDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/exceptions/TokenCreationException.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Mentor.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/SecurityConfig.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/TokenService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/SessionService.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/controller/MentorControllerIntegrationTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/controller/MentoredControllerIntegrationTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/controller/SessionControllerIntegrationTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/dto/AuthDTOTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/dto/MentorDTOTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/dto/MentoredDTOTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/mapper/SessionMapperTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/security/SecurityFilterTest.java
backend/plataforma.mentoria/src/test/java/br/edu/ufape/plataforma/mentoria/service/SessionServiceTest.java

Este PR realiza diversas melhorias e correções no código, incluindo ajustes no padrão Builder, refatorações no SecurityConfig e otimizações menores nos testes e imports. O objetivo é tornar o código mais legível, seguro e alinhado às boas práticas de Java, além de resolver issues apontadas pelo SonarCloud.  
---
- Remove construtores com muitos parâmetros e força uso do Builder pattern.  
- Resolve issues de lambda apontadas pelo SonarCloud nos testes.  
- Remove imports não utilizados.  
- Ajusta modificadores de visibilidade e lança exceções específicas onde necessário.
---
- SecurityConfig: substituição de lambdas por method references e uso de constantes para paths duplicados.  
- Refatoração geral: unificação de casos, remoção de variáveis temporárias, uso de `StringBuilder` para …

[refactor][fix] Builder pattern, SecurityConfig e ajustes internos

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/MaterialController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/ReviewDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/ReviewResponseDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/exceptions/BusinessException.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/ReviewMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/model/Review.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/ReviewRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/UserRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MaterialService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/ReviewService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/contract/ReviewServiceInterface.java

Implementa toda a lógica de serviço relacionada a Reviews de sessões
-Review
-ReviewRepository
-ReviewDTO
-ReviewResponseDTO
-ReviewMapper
-ReviewService
-ReviewServiceInterface
---
Remove imports não utlizados
---
---
---
- Closes #295 #291 
- Refers to #295 #291

Implementa lógica de serviço relacionada a Reviews de sessões

---

frontend/src/app/material-library/material-library.css
frontend/src/app/material-library/material-library.html
frontend/src/app/material-library/material-library.spec.ts
frontend/src/app/material-library/material-library.ts
frontend/src/app/services/material.ts

lógica dos botões "Filtrar" e "Limpar", que devem acionar novas chamadas à API e atualizar a lista de materiais na tela dinamicamente, sem recarregar a página.
---
N/A
---
N/A
---
---
-  x] Média: corrige comportamentos incorretos, melhora a usabilidade ou a segurança
---
- Closes #XX  

T7 - Implementar a Lógica de Exibição e Filtragem

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/MaterialService.java

Ajustes no service de Material fazendo algumas mudanças de estrutura e otimizando.
---
-N/A
---
- N/A
---
---
---
- Refers to #308

[backend][feat] Implementar Repositório e Service para a Entidade MaterialApoio

---

backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/controller/ReviewController.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/dto/SessionDTO.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/mapper/SessionMapper.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/repository/ReviewRepository.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/security/SecurityConfig.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/service/ReviewService.java
backend/plataforma.mentoria/src/main/java/br/edu/ufape/plataforma/mentoria/util/CorsConfig.java
frontend/src/app/auth/auth.service.ts
frontend/src/app/entity/dto/mentor-dto.ts
frontend/src/app/profile/feedback/feedback.component.html
frontend/src/app/profile/feedback/feedback.component.ts
frontend/src/app/profile/profile.service.ts
frontend/src/app/services/review.service.spec.ts
frontend/src/app/services/review.service.ts
frontend/src/app/session-history/session-history.component.css
frontend/src/app/session-history/session-history.component.html
frontend/src/app/session-history/session-history.component.ts
frontend/src/app/sessions/session.component.html
frontend/src/app/sessions/session.component.ts

Foi integrado o sistema de avaliações
---
- N/A
---
- N/A
---
---
---
- Closes #XX  

feat: integration reviews

---

README.md

---
---
- [...]
---
---
---
- Closes #XX  

Update project status from 'In development' to 'Completed'
